### ISSUE TITLE
Neblio commands no longer work with v.1.5.1?

### ISSUE THREAD

**Issue by Blanchot** [mouserd/neblio-slack-bot#1]
Hi,

I updated the nebliod yesterday to the latest version v.1.5.1 and while the basic slack bot commands such as 'active processes', 'memory', 'cpu', work just fine, all the neblio related commands don't seem to work.

As far as I know nothing else in my installation has changed. Has anyone else experienced this problem?

**Comment by mouserd** [comment]
Hi,

I'm running nebliod 1.5.1 and haven't had any troubles. Just make sure that when you upgraded you did install the daemon version of neblio, as opposed to the qt version. Also, maybe make sure that the daemon is indeed running.  Something like running 'nebliod getstakinginfo' from the terminal should return you some information if everything is installed correctly. 

Hope this helps!

**Comment by Blanchot** [comment]
Thanks for your reply! 

After the nebliod update I was running the daemon version and, as far as I know, it was running correctly, i.e. './nebliod getinfo' and './nebliod getstakinginfo' returned the expected information. 

After checking the .config file, poking around in your code, removing the slack-bot.log and finally rebooting neb-slack-bot.py (running in a tmux pane) the neb-slack-bot seems to be working as intended again!

Thanks again for your reply and making this helpful little bot available to the community!

**Comment by mouserd** [comment]
No problem! Glad to hear you were able to get it working again!
